export enum EventType {
    PORTFOLIO_SWITCHED = "PORTFOLIO_SWITCHED",
    PORTFOLIO_CREATED = "PORTFOLIO_CREATED",
    PORTFOLIO_UPDATED = "PORTFOLIO_UPDATED",
    PORTFOLIO_RELOAD = "PORTFOLIO_RELOAD",
    HANDLE_ERROR = "HANDLE_ERROR"
}
