/**
 * Перечисление всех типов мутаторов
 */
export enum MutationType {
    INITIALISE_STORE = "INITIALISE_STORE",
    SET_CLIENT_INFO = "SET_CLIENT_INFO",
    SET_CURRENT_PORTFOLIO = "SET_CURRENT_PORTFOLIO",
    RELOAD_PORTFOLIO = "RELOAD_PORTFOLIO",
    ACCEPT_NOTIFICATION_UPDATE = "ACCEPT_NOTIFICATION_UPDATE"
}
